### ISSUE TITLE
Disable Exceptions not working

### ISSUE THREAD

**Issue by Realium3D** [Mustard2/MustardUI#102]
Hello, I'm currently using UI version 0.26.0.020 on Blender 3.5.1 with Diffeomorphic 1.7 and I've just noticed that my Disable Exceptions list isn't having any affect when disabling morphs via the Mustard UI.

I've included a couple of screenshots to show the morph name in the list and the matching morphs shapekey on the mesh in a disabled state when morphs are disabled in the UI.

![issue_1](https://github.com/Mustard2/MustardUI/assets/119073968/ce642d05-a98d-4e66-acd2-841139f22428)
![issue_2](https://github.com/Mustard2/MustardUI/assets/119073968/161b5cad-645a-4d7f-a537-5c653509ab29)

**Comment by Mustard2** [comment]
Hi! It might be that they changed something in Diffeomorphic 1.7.
Can you send me this character so I can check?

**Comment by Mustard2** [comment]
Ah btw there might be the following bug: since the exclusion works both way (enabling and disabling), if you add those strings when the morphs are already disabled, they will be left untouched and then it might seem that the feature is not working.

To make them work, ALWAYS insert those strings when the Morphs are active. To fix the issue, copy and delete the string from the exclusion field, enable Morphs, and only then paste back the string in the exclusion field.

Let me know if it works, in the meanwhile I'll leave this open because this behavious is a bug nonetheless. :)

**Comment by Mustard2** [comment]
This seems to be fixed in #106 . Please open a new Issue if it still doesn't work. :)
