### ISSUE TITLE
Code style / Organizational improvements

### ISSUE THREAD

**Issue by Ganonmaster** [Mustard2/MustardUI#105]
Great job on this addon. It offers a lot of features that I think people enjoy. I only have some suggestions on it in terms of style and organisation.

Personally, I was having some trouble reading the code. All the different classes are in a single file that's almost 10.000 lines long. I think it might be useful to organize the project into smaller files for specific object types, or components. This might help make the code easier to read users who might want to improve the addon.

For example, all `Operator` classes could be placed in a specific operators.py file, split off the settings classes and different UI panel classes in a specific file. You could also split off and group certain components for specific "features" that not all rigs might need.

Anyway, these are just some suggestions. I personally think that it might help with making the project more accessible. I can provide a pull request if needed to clarify what I mean. :)

**Comment by Mustard2** [comment]
Hi!

Thank you this suggestion, I already thought about it and I would really like to do this but there is a major issue about refactoring everything like this.

A lot of people use this a script (i.e. a single file run in the Text Editor) in order to avoid asking their users to install a new add-on (because you know, the less you ask to users, the less they'll be confused and start asking support).

But as far as I know, please correct me if I'm wrong, it's not possible to have scripts on multiple files. :(

**Comment by Mustard2** [comment]
That being said, I'm always open to suggestion to increase readibility. I really understand it's not easy to help developing the code if everything is in one single file. :(

**Comment by Mustard2** [comment]
Version 0.30 will be a bit better, hopefully making other people more willing to contribute directly on the code.

Merge Request: #119

**Comment by Ganonmaster** [comment]
WOW! This looks like a huge improvement. I'm really, really impressed by the amount of work you did here. Props!

**Comment by Mustard2** [comment]
Thanks! I hope this will help to make it a more readable. :)
