### ISSUE TITLE
Add support for outfit collections with multiple collections inside

### ISSUE THREAD

**Issue by TheCalibrator** [Mustard2/MustardUI#108]
As of right now, doing this doesn't register any meshes inside the collections. Would be nice if it did so I can organize the outliner while also making use of the UI.

Even better would be if the collections inside the collection serve a purpose in the UI as well, but even without this it would be a big help.

**Comment by Mustard2** [comment]
Added in #106 . There is a new option in the Outfit settings (Configuration mode).

I had to change a lot of stuffs, when you have time can you check on your character if everything is working? In particular, if changing outfits, armature layers, using the clean tool, etc.. everything is working without errors.

**Comment by Mustard2** [comment]
Thanks!

For the first, unfortunately I would leave it like that because I know some people that are using the collections inside the outfits to store stuffs that they don't want to see in the main collection. If I put it on by default, when they'll udpate the UI, it might be that they'll be confused by the new feature!

As for the second, I have to check.

In the meanwhile I close, but if you find other problems, please open a new Issue. :)
