### ISSUE TITLE
No UI script generation

### ISSUE THREAD

**Issue by Mr-Lux** [Mustard2/MustardUI#54]
Hi there,

I'm using the last release 0.23 and the blender version 3.2, and don't seem to be able to generate the UI script that I find in other models done with mustardUI.

I don't know what I'm doing wrong. I suppose it should generate on ending the ui configuration but nothing happens. I still have the n-panel with the options and properties that I added, but no script file. Neither do I have an error or warning message in the console, info or log.

And while I link the collection with the rig, I do not have the access to the custom properties.

So I'm a bit lost on how to help with further info.

If you need something, tell me.

**Comment by Mustard2** [comment]
Hi!

Maybe it's not completely clear from the documentation, but the things should work like this:
- if you want to add the UI to a model, do NOT install it as a Blender addon, but run it as a script: https://github.com/Mustard2/MustardUI/wiki/Installation-and-Configuration#installation
- go thorugh the configuration
- then at the end, with Maintenance Tools enabled in the Settings, in the same panel a "Register UI" button should appear. Clicking on it, the UI script will be registered (i.e., the Register option in the Text Editor is enabled so that the UI is run every time you load the model), and the mustard_ui.py script will be appended whenever the model is appended on other scenes

This is because, instead of storing the informations on a script (which in my opinion is not a great option for a lot of reasons), the UI data are actually stored in the Armature of the model. This also ensures that users of your models do not have to deal with scripts, and they can also update the UI just downloading the script from this github without new configurations.

**Comment by Mr-Lux** [comment]
I does. I was using it as a add-on instead of a direct script. Thank you for the quick answer.

**Comment by Mustard2** [comment]
Added a comment in the documentation.
