### ISSUE TITLE
Eevee optimized normals driver

### ISSUE THREAD

**Issue by datquil** [Mustard2/MustardUI#72]
A driver (Copy as New Driver) based on eevee optimized normals property uses the [scene](https://uploadir.com/u/cylxafjm). From experience I know that it creates a problem when we append a model - it [appends additional scene](https://uploadir.com/u/baqj8hfl) to the new project file and the driver in the "Scene.001" breaks.

I have tried creating the driver manually [like so](https://uploadir.com/u/ly09zqmo) but it doesn't seem to work.

Shouldn't it create a driver just like it does for [subdivision](https://uploadir.com/u/gfic1f8s) or smooth correction properties?

**Comment by Mustard2** [comment]
Hi!

Firstly, subdivision or smooth correction global properties in both body, outfits and hair are not using drivers to work. They do if you create custom properties though, but this depends on your setup.
So, why did you create some drivers for subdivision? Just to understand, if there is something that the UI might have to do instead of having to create drivers on those, I can add it by default. :-)

For your question, the Eevee Optimized Normals are stored in the Scene rather than the Armature because they affect all the materials in the Scene. If I put it in the Armature, it would create issues when you switch to other MustardUI-based models on the same scene.
That being said, I was wondering, why do you need such driver? Maybe I can help with an alternative or a fix.

**Comment by datquil** [comment]
So the drivers for subdivision are probably not necessary since you have those options in outfits list which I wasn't sure if I want to use.

What I'm trying to do is to have some sort of property that tells me whether the model uses eevee optimized normals or regular ones and use that property [as a driver](https://uploadir.com/u/xtb6c6mr) to switch between 2 textures. Basically whether you use eevee or cycles but the driver cannot have a scene as the ID type.

Previously I had a custom property on the rig.

**Comment by Mustard2** [comment]
If you just need to know if you're using Eevee or Cycles there are two ways if you're dealing with shaders:
- use the material output node to specify the engine, you can choose between Cycles, Eevee and All. This is advised as Blender knows what to load and what not, with Mix nodes it might load textures that are not actually used in one engine.
- use the Scene property for the engine (with a clamp because Eevee = 0 and Cycles = 2)

![Immagine 2022-08-10 212342](https://user-images.githubusercontent.com/60780948/184003030-e3e4cf4d-3a22-4a26-931d-9147f8a7434b.png)

**Comment by datquil** [comment]
Yes I know that the eevee normals aren't for cycles. My assumption was that if you were to use eevee you would use the optimized normals and then I would switch between 2 textures (long story short - the "eevee" texture doesn't look good in cycles and vice versa). But now that I think about it eevee normals are optional so my solution wouldn't really work here.

Anyway, I guess I'll use the material output node even though it looks kinda messy. The second option is a no go - it works fine within the model's blend file but when you append the model the driver messes up. Thanks.
