### ISSUE TITLE
Body and outfit properties reset when using smart search to add new outfits

### ISSUE THREAD

**Issue by mokujinh** [Mustard2/MustardUI#93]
As the title says, It happens mostly with float sliders, some customized properties get reseted to a default value once you add an outfit by using the search tool in the UI. i.e.: When I add a new outfit, a previously custom made "normal strength" property linked to the body materials with a default value of "0.0" with an end Value of "5.0" and a set default value of "1.0" gets replaced by other settings, making the end value 1.0 and the default 0.0. Same happen with multiple custom made values, so, I have to remember which and what the values were after I add a new outfit each time. 
More of a QoL thing but I think it's worth mentioning.

**Comment by Mustard2** [comment]
Hi!

Yes you're right, this happens because whenever you use that button, it will also automatically call the smart search for body properties, removing all the ones that are added as MustardUI Float/Bool etc..

To solve this:
- either I split the button (which might be a bit unintuitive for people?)
- call a window when you press the button to decide what to actually search

As a workaround, you can add outfits right clicking on the collections (while in configuration mode) instead of using that button.

**Comment by Mustard2** [comment]
Solved in 0.26.0.

Now the Smart Check tool will ask for which sections to modify.

![image](https://user-images.githubusercontent.com/60780948/213934377-a08fa5ab-37fd-4d92-bd79-d6fcc2ef57ea.png)

In addition, you can now smart check only the outfits with a dedicated button.

![image](https://user-images.githubusercontent.com/60780948/213934418-4cedef22-fe9d-4adb-9820-64d3d92e66fe.png)
